= INEX/TECH Documentation

Welcome to the INEX/TECH documentation site.

To see a larger view of an image, right-click on it and select "Open image in new tab"

To save a document as PDF:

* Expand any "Click to..." (collapsed) items, such as the Table of Contents, Related Documents and Notes

* To ensure that all graphics will appear completely
in the PDF, scroll down slowly from the top of
the online file and wait until each graphic loads
completely.

* Use your browser's Print command (CTRL-p)

* (Chrome) Select Save as PDF as the destination

* (Chrome) In the More Settings section:
** Select Paper Size of A4
** Set the Margins to Custom:
*** Click in the top margin
number box on the page display, and set it to 0.5"
*** The left, right and bottom margins can remain at their
defaults (should be 0.5")
** Check the Background Graphics box (to show the shading in the Notes, and in the table headers)
** Optional: If you check Headers and Footers, the header will have the current date/time,
and the footer will have the site URL and page number



