//!sectnum momentarily stops section numbering
// but decided to leave in since all these 
// warnings will be at the end and should 
// be seen in the TOC with numbers
//:!sectnums:

=== Notice
INEX Technologies reserves the right to improve and enhance its product offerings. Thus, the illustrations and descriptions presented in this manual may differ in some respect from the products you receive.

Technical specifications are subject to change without notice.

In addition, please note that some figures are not drawn to scale, in order to illustrate the addressed issue more effectively.

All third-party trademarks are the property of their respective owners.

INEX Technologies cannot be held liable for technical and editorial omissions or errors made in this document; nor for incidental or consequential damages resulting from the furnishing, performance or use of this document.

Actions or circumstances that void the warranty are improper usage, improper handling without adequate electrostatic discharge (ESD) protection, defects resulting from natural disaster (fire, flood etc.) and unauthorized modifications or repair.

Power undervoltage, overvoltage and/or incorrect polarity will damage the unit and will void the warranty.

It is your responsibility to ensure that all wires connected to INEX Technologies' products have appropriate surge protection. Any damage due to electrical spikes (for example, lightning) is not covered by the warranty.

No part of this document may be reproduced in any form without permission from INEX Technologies.
