//!sectnum momentarily stops section numbering
// but decided to leave in since all these 
// warnings will be at the end and should 
// be seen in the TOC with numbers
//:!sectnums:

// These attribute definitions are for
// test purposes only
// they will normally be defined in
// the main document using this file
// as an include
// :xref-type-IZA800G:
// :!xref-type-IZ600F:
// :generic-camera-name: ALPR Camera System

=== Safety Precautions

[CAUTION]
===============================

*BEWARE OF RISK OF ELECTRICAL SHOCK*

*REFER SERVICING TO QUALIFIED SERVICE PERSONNEL*
===============================

[IMPORTANT]
===============================
This product must be used in compliance with local laws and regulations.

All network cable extensions and repeaters must be shielded.

Power undervoltage, overvoltage and/or incorrect polarity will damage the unit and will void the warranty.
===============================

* Please read this guide carefully before installing the illuminator.
* Keep this guide for future reference.
* Do not disassemble the illuminator unit.
Repair or replacement of parts for this
unit should be supplied by {compname-long}, and installed by qualified service personnel.
* Handle and store the illuminator
with care.
* Do not drop the unit or subject it to physical shock.
* Do not allow water (e.g. rain) to enter the unit.
* Do not handle the illuminator unless you have adequate electrostatic discharge (ESD) protection; otherwise, the warranty will be void.
* You must request that your {compname-long}-certified service
technician install lightning and electrical
surge protection on all wiring connected
to {compname-possess} products.
The warranty does not cover surge or
lightning protection.
* Do not use the unit outside of its temperature
, humidity and power source ratings as
noted in its technical specifications.
* To avoid heat accumulation/overheating, use
sufficient ventilation in the unit's
operating environment.
* Do not connect several devices to one power adapter since adapter overload may cause overheating or a fire hazard.
* Stop using the unit immediately if it emits smoke, or if you notice an abnormal smell or sound. In such cases, please contact us. Do not attempt to repair the unit by yourself!

include::ROOT:partial$p-illum-eye-safety.adoc[]